Repository SayedAlesawy/Videra-Ingestion, pull requests merged in 2020-05, with the labels that each got.

#5 [Feature][Orchestrator] Enhance Health Check Monitor
  orchestrator/config/config.go
  orchestrator/config/config_files/health_check_monitor.yaml
  orchestrator/config/types.go
  orchestrator/drivers/tcp/tcp.go
  orchestrator/drivers/tcp/types.go
  orchestrator/go.mod
  orchestrator/go.sum
  orchestrator/health/health.go
  orchestrator/health/types.go
  orchestrator/main.go
  orchestrator/process/process.go
  orchestrator/process/types.go
  orchestrator/utils/errors/errors.go
Labels: enhancement

#8 [Enhancement] Reduce monitor CPU usage
  orchestrator/config/config_files/health_check_monitor.yaml
  orchestrator/config/types.go
  orchestrator/health/health.go
  orchestrator/health/types.go
Labels: enhancement

#7 [Enhancement] Use custom image in Dockerfile
  Dockerfile
  docker-compose.yml
Labels: enhancement

#10 fix/terminate main process on first signal
  executor/heartbeat.py
  executor/main.py
Labels: bug

#11 [Feature][Orchestrator] Add Processes Manager
  docker-compose.yml
  executor/heartbeat.py
  executor/main.py
  orchestrator/config/config.go
  orchestrator/config/config_files/health_check_monitor.yaml
  orchestrator/config/config_files/processes_manager.yaml
  orchestrator/config/health_check_monitor.go
  orchestrator/config/processes_manager.go
  orchestrator/config/types.go
  orchestrator/health/health.go
  orchestrator/health/types.go
  orchestrator/main.go
  orchestrator/process/process.go
  orchestrator/process/processes_manager.go
  orchestrator/process/types.go
  orchestrator/process/utils.go
Labels: enhancement, feature

#13 [Feature][Orchestrator] Added params utility package
  orchestrator/utils/file/file.go
  orchestrator/utils/params/params.go
  orchestrator/utils/params/types.go
Labels: feature

#14 feat/ params parsing for execution
  executor/main.py
  executor/params_parser.py
  orchestrator/Makefile
  orchestrator/config/config_files/processes_manager.yaml
  orchestrator/config/processes_manager.go
  orchestrator/process/process.go
  orchestrator/process/types.go
  orchestrator/process/utils.go
  orchestrator/utils/params/params.go
  orchestrator/utils/params/types.go
Labels: feature
