Repository SayedAlesawy/Videra-Ingestion, pull requests merged in 2020-06, with the labels that each got.

#20 Separate processes args
  orchestrator/config/config_files/processes_manager.yaml
  orchestrator/config/processes_manager.go
  orchestrator/process/process.go
  orchestrator/process/types.go
  orchestrator/process/utils.go
Labels: enhancement

#21 Executor communication logic over redis
  executor/heartbeat.py
  executor/main.py
  executor/params_parser.py
  executor/receiver.py
  executor/requirements.txt
Labels: feature

#24 [Fix][Orchestrator] Use jid instead of job md5 hash
  orchestrator/ingest/ingest.go
Labels: fix

#23 add execution logic
  executor/execution_worker.py
  executor/heartbeat.py
  executor/main.py
  executor/requirements.txt
  orchestrator/output/.keep
Labels: feature

#25 [Feature][Orchestrator] Auto terminate when ingestion is done
  orchestrator/config/config_files/ingestion_manager.yaml
  orchestrator/config/ingestion_manager.go
  orchestrator/ingest/cache.go
  orchestrator/ingest/ingest.go
  orchestrator/ingest/job_completed_handler.go
  orchestrator/ingest/types.go
  orchestrator/ingest/worker_crashed_handler.go
  orchestrator/main.go
Labels: feature
