Repository SayedAlesawy/Videra-Ingestion, pull requests merged in 2020-08, with the labels that each got.

#29 feat/ database driver implementation
  actions/db/db_driver.py
  actions/merger/.keep
  actions/merger/merge.py
  actions/merger/params_parser.py
  actions/merger/setup.cfg
  actions/requirements.txt
  actions/task_manager.py
Labels: feature

#30 add more verbosity to job state in processes
  actions/executor/execution_worker.py
  actions/flow_manager.py
  actions/merger/merge.py
  actions/task_manager.py
Labels: enhancement

#31 [Fix][Orchestrator] Init workers map on start
  actions/flow_manager.py
  actions/heartbeat.py
  actions/merger/merge.py
  actions/task_manager.py
  ingest/cache.go
  ingest/ingest.go
  ingest/worker_crashed_handler.go
  ingest/worker_online_handler.go
  main.go
Labels: fix

#32 support code file parameter
  Makefile
  actions/db/db_driver.py
  actions/executor/execution_worker.py
  actions/params_parser.py
  actions/task_manager.py
  config/config_files/ingestion_manager.yaml
  config/config_files/processes_manager.yaml
  utils/params/params.go
  utils/params/types.go
Labels: enhancement
